default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME", "line_of_thought") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: line_of_thought_development

test:
  <<: *default
  database: line_of_thought_test

production:
  <<: *default
  database: line_of_thought_production
  url: <%= ENV["DATABASE_URL"] %>
